import { expect, test } from "@playwright/test";
import { signIn } from "./helpers";

test("missed work, durable lock and isolated what-if keep the selected plan under user control", async ({ page }) => {
  test.setTimeout(60000);
  await signIn(page, "b");
  const title = `Adaptation example ${Date.now()}`;
  const day = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  const taskForm = page.getByRole("form", { name: "Add task", exact: true });
  await taskForm.getByLabel("Task name", { exact: true }).fill(title);
  await taskForm.getByLabel("Remaining minutes", { exact: true }).fill("60");
  await taskForm.getByLabel("Deadline (UTC)", { exact: true }).fill(day);
  await taskForm.getByRole("button", { name: "Add task", exact: true }).click();
  await expect(page.locator(".task-list > ul").getByText(title, { exact: true })).toBeVisible();
  await page.getByLabel("Available from (UTC)", { exact: true }).fill(`${day}T09:00`);
  await page.getByLabel("Available until (UTC)", { exact: true }).fill(`${day}T17:00`);
  await page.getByRole("button", { name: "Add available time" }).click();
  await expect(page.getByText("Available time saved")).toBeVisible();
  await page.getByRole("button", { name: "Generate plan", exact: true }).click();
  const activate = page.getByRole("button", { name: "Activate this plan", exact: true });
  await expect(activate).toBeVisible({ timeout: 20000 });
  await activate.click();
  await expect(page.getByText("Plan activated", { exact: true })).toBeVisible();
  const activeBefore = await (await page.request.get("/api/v1/active-plan")).json();
  await page.getByText("Record progress or missed work", { exact: true }).click();
  await page.getByRole("combobox", { name: "Task to update", exact: true }).selectOption({ label: title });
  await page.getByLabel("New remaining estimate (minutes)", { exact: true }).fill("60");
  await page.getByRole("button", { name: "Save progress", exact: true }).click();
  await expect(page.getByText("Progress recorded", { exact: true })).toBeVisible();
  await expect(page.getByText("0 minutes observed · 60 minutes remaining", { exact: true })).toBeVisible();
  await page.getByText("Adjust blocks in your active plan", { exact: true }).click();
  const activeBlock = page.locator(".active-blocks > li").filter({ has: page.getByRole("heading", { name: title, exact: true }) });
  await activeBlock.getByRole("button", { name: "Lock this block", exact: true }).click();
  await expect(activeBlock.getByRole("button", { name: "Unlock this block", exact: true })).toBeVisible();
  await page.getByText("Explore a change before applying it", { exact: true }).click();
  await page.getByLabel("Extra time from (UTC)").fill(`${day}T18:00`);
  await page.getByLabel("Extra time until (UTC)").fill(`${day}T20:00`);
  const availabilityBefore = await (await page.request.get("/api/v1/availability")).json();
  await page.getByRole("button", { name: "Preview changes", exact: true }).click();
  const apply = page.getByRole("button", { name: "Apply these input changes", exact: true });
  await expect(apply).toBeEnabled({ timeout: 20000 });
  expect((await (await page.request.get("/api/v1/active-plan")).json()).id).toBe(activeBefore.id);
  expect((await (await page.request.get("/api/v1/availability")).json()).windows).toEqual(availabilityBefore.windows);
  await apply.click();
  await expect(page.getByText("Inputs updated. Review and activate the new plan when it is ready.", { exact: true })).toBeVisible();
  expect((await (await page.request.get("/api/v1/active-plan")).json()).id).toBe(activeBefore.id);
  await page.screenshot({ path: "docs/evidence/raw/adaptation-active.png", fullPage: true });
});
