"""add explicit progress protected work and what if previews

Revision ID: 0006_adaptation
Revises: b98ef88cd5bf
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0006_adaptation'
down_revision = 'b98ef88cd5bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('what_ifs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('candidate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('base_candidate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'id')
    )
    op.create_index(op.f('ix_what_ifs_owner_id'), 'what_ifs', ['owner_id'], unique=False)
    op.create_table('protected_work',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('"end" > start'),
    sa.ForeignKeyConstraint(['owner_id', 'task_id'], ['tasks.owner_id', 'tasks.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'id')
    )
    op.create_table('work_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('observed_minutes', sa.Integer(), nullable=False),
    sa.Column('new_remaining_minutes', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('correction_of', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('block_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('new_remaining_minutes >= 0'),
    sa.CheckConstraint('observed_minutes >= 0'),
    sa.ForeignKeyConstraint(['owner_id', 'correction_of'], ['work_logs.owner_id', 'work_logs.id'], ),
    sa.ForeignKeyConstraint(['owner_id', 'proposal_id', 'block_id'], ['proposal_blocks.owner_id', 'proposal_blocks.proposal_id', 'proposal_blocks.id'], ),
    sa.ForeignKeyConstraint(['owner_id', 'task_id'], ['tasks.owner_id', 'tasks.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'id')
    )
    op.create_index(op.f('ix_work_logs_owner_id'), 'work_logs', ['owner_id'], unique=False)
    op.add_column('jobs', sa.Column('kind', sa.String(length=20), server_default='REPLAN', nullable=False))
    op.add_column('jobs', sa.Column('what_if_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_job_owned_what_if', 'jobs', 'what_ifs', ['owner_id', 'what_if_id'], ['owner_id', 'id'])
    op.execute("""CREATE FUNCTION reject_work_log_change() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'work logs are append only; add a correction'; END; $$""")
    op.execute("""CREATE TRIGGER append_only_work_logs BEFORE UPDATE OR DELETE ON work_logs
      FOR EACH ROW EXECUTE FUNCTION reject_work_log_change()""")
    op.execute("""CREATE FUNCTION protect_what_if_inputs() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN IF NEW.changes IS DISTINCT FROM OLD.changes
      OR NEW.base_revision IS DISTINCT FROM OLD.base_revision
      OR NEW.owner_id IS DISTINCT FROM OLD.owner_id
      OR (OLD.candidate IS NOT NULL AND NEW.candidate IS DISTINCT FROM OLD.candidate)
      THEN RAISE EXCEPTION 'what-if inputs and completed result are immutable'; END IF;
      RETURN NEW; END; $$""")
    op.execute("""CREATE TRIGGER immutable_what_if_inputs BEFORE UPDATE ON what_ifs
      FOR EACH ROW EXECUTE FUNCTION protect_what_if_inputs()""")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP TRIGGER immutable_what_if_inputs ON what_ifs')
    op.execute('DROP FUNCTION protect_what_if_inputs()')
    op.execute('DROP TRIGGER append_only_work_logs ON work_logs')
    op.execute('DROP FUNCTION reject_work_log_change()')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_job_owned_what_if', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'what_if_id')
    op.drop_column('jobs', 'kind')
    op.drop_index(op.f('ix_work_logs_owner_id'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_table('protected_work')
    op.drop_index(op.f('ix_what_ifs_owner_id'), table_name='what_ifs')
    op.drop_table('what_ifs')
    # ### end Alembic commands ###
