"""enforce immutable scheduling payloads and owner links

Revision ID: 2d83e6cceaea
Revises: 62879c45fc31
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "2d83e6cceaea"
down_revision = "62879c45fc31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.create_foreign_key(
        "fk_publication_owned_block",
        "publication_operations",
        "proposal_blocks",
        ["owner_id", "proposal_id", "block_id"],
        ["owner_id", "proposal_id", "id"],
    )
    op.create_foreign_key(
        "fk_active_proposal_owner",
        "user_planning_state",
        "proposals",
        ["owner_id", "active_proposal_id"],
        ["owner_id", "id"],
        use_alter=True,
    )
    op.execute("""CREATE FUNCTION reject_snapshot_change() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'immutable snapshot cannot be changed'; END; $$""")
    op.execute("""CREATE TRIGGER immutable_snapshot_guard
      BEFORE UPDATE OR DELETE ON immutable_snapshots
      FOR EACH ROW EXECUTE FUNCTION reject_snapshot_change()""")
    op.execute("""CREATE FUNCTION reject_proposal_payload_change()
      RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN IF NEW.candidate IS DISTINCT FROM OLD.candidate
        OR NEW.snapshot_id IS DISTINCT FROM OLD.snapshot_id
        OR NEW.owner_id IS DISTINCT FROM OLD.owner_id
        OR NEW.planning_revision IS DISTINCT FROM OLD.planning_revision
        OR NEW.calendar_revision IS DISTINCT FROM OLD.calendar_revision
        THEN RAISE EXCEPTION 'immutable proposal payload cannot be changed'; END IF;
        RETURN NEW; END; $$""")
    op.execute("""CREATE TRIGGER immutable_proposal_payload_guard BEFORE UPDATE ON proposals
      FOR EACH ROW EXECUTE FUNCTION reject_proposal_payload_change()""")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER immutable_proposal_payload_guard ON proposals")
    op.execute("DROP FUNCTION reject_proposal_payload_change()")
    op.execute("DROP TRIGGER immutable_snapshot_guard ON immutable_snapshots")
    op.execute("DROP FUNCTION reject_snapshot_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_active_proposal_owner", "user_planning_state", type_="foreignkey")
    op.drop_constraint("fk_publication_owned_block", "publication_operations", type_="foreignkey")
    op.drop_column("jobs", "result")
    # ### end Alembic commands ###
