"""durable scheduling jobs and proposals

Revision ID: 62879c45fc31
Revises: e3b311ba42f4
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "62879c45fc31"
down_revision = "e3b311ba42f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "immutable_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(
        op.f("ix_immutable_snapshots_owner_id"), "immutable_snapshots", ["owner_id"], unique=False
    )
    op.create_table(
        "owner_dispatch_state",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("last_dispatch_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("planning_revision", sa.Integer(), nullable=False),
        sa.Column("calendar_revision", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("fencing_token", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("obsolete", sa.Boolean(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("proposal_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id", "snapshot_id"],
            ["immutable_snapshots.owner_id", "immutable_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index("ix_jobs_owner_created", "jobs", ["owner_id", "created_at"], unique=False)
    op.create_index(
        "uq_running_job_owner",
        "jobs",
        ["owner_id"],
        unique=True,
        postgresql_where=sa.text("state = 'RUNNING'"),
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("planning_revision", sa.Integer(), nullable=False),
        sa.Column("calendar_revision", sa.Integer(), nullable=False),
        sa.Column("candidate", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("publication_state", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id", "snapshot_id"],
            ["immutable_snapshots.owner_id", "immutable_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(op.f("ix_proposals_owner_id"), "proposals", ["owner_id"], unique=False)
    op.create_table(
        "proposal_blocks",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "proposal_id"],
            ["proposals.owner_id", "proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id"],
            ["tasks.owner_id", "tasks.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "proposal_id", "id"),
    )
    op.create_table(
        "publication_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "proposal_id"],
            ["proposals.owner_id", "proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "proposal_id", "block_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_operations")
    op.drop_table("proposal_blocks")
    op.drop_index(op.f("ix_proposals_owner_id"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index(
        "uq_running_job_owner", table_name="jobs", postgresql_where=sa.text("state = 'RUNNING'")
    )
    op.drop_index("ix_jobs_owner_created", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("owner_dispatch_state")
    op.drop_index(op.f("ix_immutable_snapshots_owner_id"), table_name="immutable_snapshots")
    op.drop_table("immutable_snapshots")
    # ### end Alembic commands ###
