"""identity ownership and transactional inputs

Revision ID: e3b311ba42f4
Revises: 0001_bootstrap
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e3b311ba42f4"
down_revision = "0001_bootstrap"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject"),
    )
    op.create_table(
        "login_flows",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        sa.Column("verifier", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=300), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_owner_id"), "audit_events", ["owner_id"], unique=False)
    op.create_table(
        "availability_rules",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("windows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "browser_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_browser_sessions_owner_id"), "browser_sessions", ["owner_id"], unique=False
    )
    op.create_table(
        "command_receipts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=300), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "operation", "key"),
    )
    op.create_index(
        op.f("ix_command_receipts_expires_at"), "command_receipts", ["expires_at"], unique=False
    )
    op.create_table(
        "fixed_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(op.f("ix_fixed_events_owner_id"), "fixed_events", ["owner_id"], unique=False)
    op.create_table(
        "pending_replans",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("desired_revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("explicit", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "enqueued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("remaining_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state IN ('TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED')"),
        sa.CheckConstraint("priority >= 1 AND priority <= 5"),
        sa.CheckConstraint("remaining_minutes >= 0"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(
        "ix_tasks_owner_created_id", "tasks", ["owner_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "user_planning_state",
        sa.Column("active_proposal_id", sa.Uuid(), nullable=True),
        sa.Column("calendar_revision", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint("revision >= 0"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["identities.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "dependency_edges",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("predecessor_id", sa.Uuid(), nullable=False),
        sa.Column("successor_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("predecessor_id <> successor_id"),
        sa.ForeignKeyConstraint(
            ["owner_id", "predecessor_id"],
            ["tasks.owner_id", "tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "successor_id"],
            ["tasks.owner_id", "tasks.id"],
        ),
        sa.PrimaryKeyConstraint("owner_id", "predecessor_id", "successor_id"),
    )
    op.execute("""CREATE FUNCTION reject_audit_mutation() RETURNS trigger AS $$
        BEGIN RAISE EXCEPTION 'audit events are append-only'; END;
        $$ LANGUAGE plpgsql""")
    op.execute(
        "CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON audit_events "
        "FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dependency_edges")
    op.drop_table("user_planning_state")
    op.drop_index("ix_tasks_owner_created_id", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("pending_replans")
    op.drop_index(op.f("ix_fixed_events_owner_id"), table_name="fixed_events")
    op.drop_table("fixed_events")
    op.drop_index(op.f("ix_command_receipts_expires_at"), table_name="command_receipts")
    op.drop_table("command_receipts")
    op.drop_index(op.f("ix_browser_sessions_owner_id"), table_name="browser_sessions")
    op.drop_table("browser_sessions")
    op.drop_table("availability_rules")
    op.drop_index(op.f("ix_audit_events_owner_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.execute("DROP FUNCTION reject_audit_mutation()")
    op.drop_table("login_flows")
    op.drop_table("identities")
    # ### end Alembic commands ###
